# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample the latent thresholds through griddy Gibbs
#' 
#' This function implements the griddy Gibbs sampler for the thresholds
#'
#' @param Achg1 TODO
#' @param SIGMAS1 TODO
#' @param SIGMAS2 TODO
#' @param threshgrid TODO
#' @param Aapprox TODO
get_threshold <- function(Achg1, SIGMAS1, SIGMAS2, threshgrid, Aapprox) {
    .Call('_threshtvp_get_threshold', PACKAGE = 'threshtvp', Achg1, SIGMAS1, SIGMAS2, threshgrid, Aapprox)
}

KF <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_KF', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

get_lik <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_get_lik', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

KF_fast <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_KF_fast', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

KF_MH <- function(y, Z, Ht, Qtt, m, p, t, B0, V0) {
    .Call('_threshtvp_KF_MH', PACKAGE = 'threshtvp', y, Z, Ht, Qtt, m, p, t, B0, V0)
}

